ToDoListWithDjango/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('task/',include('task.urls')),
]

task/urls.py
from django.urls import path
from . import views
app_name = 'task'
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
]

task/models.py
from django.db import models

# Create your models here.

task/views.py
from os import name
from django.shortcuts import render
from django.http import HttpResponse
import task
from django import forms
from django.http.response import HttpResponseRedirect
from django.http import HttpResponseRedirect
from django.urls import reverse
class AddTaskForm(forms.Form):
    task = forms.CharField(label='Task Name')

def index(request):
    if 'tasks' not in request.session:
        request.session['tasks'] = []
    return render(request, 'task/index.html', {'tasks': request.session['tasks']})
def add(request):
    if request.method == 'POST':
        form= AddTaskForm(request.POST)
        if form.is_valid():
            task= form.cleaned_data['task']
            request.session['tasks']+=[task]
            return HttpResponseRedirect(reverse('task:index'))
        else:
            return render(request, 'task/add.html', {'form': form})
    return render(request, 'task/add.html',{
        'form': AddTaskForm()
    })
    

task/templates/task/add.html
{% extends "task/layout.html" %}
{% block title %}Add List{% endblock title %}
{% block body %}
<h2>Add</h2>
<form action="{% url 'task:add' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <!-- <input type="text"> -->
    <br><br>
    
    <input type="submit" class="button" value="Add">
</form>
<br>
<a href="{% url 'task:index' %}" class="button">View</a>
{% endblock %}

task/templates/task/index.html
{% extends "task/layout.html" %}
{% load static %}
{% block title %}To Do List{% endblock title %}
{% block body %}
<h2>My To Do List</h2>
<ul>
{% for task in tasks %}
    <li>{{ task }}</li>
    {% empty %}
    <li>No tasks</li>
{% endfor %}
</ul>
<a href="{% url 'task:add' %}" class="button">Add</a>
{% endblock %}

task/templates/task/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Layout web{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>